SRC_DIR := src
INC_DIR := include
BUILD_DIR := build
TARGET_BUILD_DIR := $(BUILD_DIR)/targets/$(TARGET_TRIPLE)
HOST_BUILD_DIR := $(TARGET_BUILD_DIR)/host
PROGRAM_BUILD_DIR := $(TARGET_BUILD_DIR)/toolchains/$(BUILD_TOOLCHAIN)
PROGRAM_OBJ_DIR := $(PROGRAM_BUILD_DIR)/obj
PROGRAM_BIN_DIR := $(PROGRAM_BUILD_DIR)/bin
TARGET := $(PROGRAM_BIN_DIR)/$(TARGET_NAME)
DIST_DIR := $(TARGET_BUILD_DIR)/dist
VISUAL_ARTIFACT_ROOT ?= visual_artifacts
VISUAL_ARTIFACT_OUTPUT ?= $(VISUAL_ARTIFACT_ROOT)/datalab_first_frame.bmp
VULKAN_ROLLOUT_DIR := $(abspath $(BUILD_DIR)/vulkan-rollout)
VULKAN_ROLLOUT_INITIAL_CAPTURE := $(VULKAN_ROLLOUT_DIR)/datalab-initial.bmp
VULKAN_ROLLOUT_RESIZED_CAPTURE := $(VULKAN_ROLLOUT_DIR)/datalab-resized.bmp
VULKAN_ROLLOUT_LOG := $(VULKAN_ROLLOUT_DIR)/datalab-vulkan.log
PACKAGE_VULKAN_ROLLOUT_DIR := $(abspath $(BUILD_DIR)/package-vulkan-rollout)
PACKAGE_VULKAN_INITIAL_CAPTURE := $(PACKAGE_VULKAN_ROLLOUT_DIR)/datalab-package-initial.bmp
PACKAGE_VULKAN_RESIZED_CAPTURE := $(PACKAGE_VULKAN_ROLLOUT_DIR)/datalab-package-resized.bmp
PACKAGE_VULKAN_LOG := $(PACKAGE_VULKAN_ROLLOUT_DIR)/datalab-package-vulkan.log
CANONICAL_SHARED_ROOT ?= ../shared

SHARED_ROOT ?= third_party/codework_shared
SHARED_BUILD_DIR := $(TARGET_BUILD_DIR)/shared
KIT_GRAPH_TS_BUILD_DIR := $(SHARED_BUILD_DIR)/kit_graph_timeseries
KIT_WORKSPACE_AUTHORING_BUILD_DIR := $(SHARED_BUILD_DIR)/kit_workspace_authoring
KIT_RENDER_BUILD_DIR := $(SHARED_BUILD_DIR)/kit_render
KIT_UI_DIR := $(SHARED_ROOT)/kit/kit_ui

PACKAGE_APP_DIR := $(DIST_DIR)/$(PACKAGE_APP_NAME)
PACKAGE_CONTENTS_DIR := $(PACKAGE_APP_DIR)/Contents
PACKAGE_MACOS_DIR := $(PACKAGE_CONTENTS_DIR)/MacOS
PACKAGE_RESOURCES_DIR := $(PACKAGE_CONTENTS_DIR)/Resources
PACKAGE_FRAMEWORKS_DIR := $(PACKAGE_CONTENTS_DIR)/Frameworks
PACKAGE_INFO_PLIST_SRC := tools/packaging/macos/Info.plist
PACKAGE_LAUNCHER_SRC := tools/packaging/macos/datalab-launcher
PACKAGE_DYLIB_BUNDLER := tools/packaging/macos/bundle-dylibs.sh
PACKAGE_APP_RM_GUARD := tools/packaging/macos/guard-app-rm-dir.sh
PACKAGE_APP_ICON_NAME := AppIcon
PACKAGE_APP_ICON_FILE := $(PACKAGE_APP_ICON_NAME).icns
PACKAGE_LOCAL_ICON_DIR := tools/packaging/macos/local_app_icon
PACKAGE_APP_ICON_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_FILE)
PACKAGE_APP_ICONSET_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_NAME).iconset
PACKAGE_BUNDLED_ICON_PATH := $(PACKAGE_RESOURCES_DIR)/$(PACKAGE_APP_ICON_FILE)
PACKAGE_SELF_TEST_ROOT := $(TARGET_BUILD_DIR)/package-self-test
PACKAGE_SELF_TEST_HOME := $(PACKAGE_SELF_TEST_ROOT)/home
PACKAGE_SELF_TEST_TMP := $(PACKAGE_SELF_TEST_ROOT)/tmp
PACKAGE_SELF_TEST_OUTPUT := $(PACKAGE_SELF_TEST_ROOT)/launcher_self_test.txt
DESKTOP_APP_DIR ?= $(HOME)/Desktop/$(PACKAGE_APP_NAME)
PACKAGE_ADHOC_SIGN_IDENTITY ?= -

RELEASE_VERSION ?= $(strip $(shell cat "$(VERSION_FILE)" 2>/dev/null))
ifeq ($(RELEASE_VERSION),)
RELEASE_VERSION := 0.1.0
endif
RELEASE_PROGRAM_KEY := $(PROGRAM_KEY)
RELEASE_ARTIFACT_BASENAME := $(RELEASE_PRODUCT_NAME)-$(RELEASE_VERSION)-$(RELEASE_PLATFORM)-$(RELEASE_ARCH)-$(RELEASE_CHANNEL)
# May be supplied by the Production Registry as a job-scoped relative root.
# Keep the ordinary developer default for manual local releases.
RELEASE_ROOT ?= build/release
RELEASE_DIR := $(RELEASE_ROOT)
RELEASE_APP_ZIP := $(RELEASE_DIR)/$(RELEASE_ARTIFACT_BASENAME).zip
RELEASE_APP_ZIP_SHA256 := $(RELEASE_APP_ZIP).sha256
RELEASE_MANIFEST := $(RELEASE_DIR)/$(RELEASE_ARTIFACT_BASENAME).manifest.txt
